name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install gcc
      run: |
          wget --quiet https://kayari.org/gcc-latest/gcc-latest.deb \
          && sudo dpkg -i gcc-latest.deb
          echo "/opt/gcc-latest/bin" >> $GITHUB_PATH
          echo "LD_RUN_PATH=/opt/gcc-latest/lib64" >> $GITHUB_ENV
    - name: validate gcc
      run: echo | g++ -xc++ -E --verbose -
    - name: install apt packages
      run: sudo apt update && sudo apt install g++-14 nlohmann-json3-dev
    - name: build
      run: CXXVER=26 ./build.py /build_system /linux /process
