name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: install apt packages
      run: sudo apt update && sudo apt install g++-14 nlohmann-json3-dev bzip2 flex build-essential

    - name: get gcc commit
      id: get-gcc-commit
      run: |
        echo "commit=$(git rev-parse HEAD:submodules/gcc)" >> $GITHUB_OUTPUT
      shell: bash

    - name: cache gcc install
      id: cache-gcc
      uses: actions/cache@v4
      with:
        path: /opt/GCC
        key: ${{ runner.os }}-gcc-${{ steps.get-gcc-commit.outputs.commit }}

    - name: install gcc
      run: |
        git submodule update --init --depth=1 -- submodules/gcc
        submodules/build-gcc.sh --install
      if: steps.cache-gcc.outputs.cache-hit != 'true'

    - name: activate gcc
      run: |
        echo "/opt/GCC/bin" >> $GITHUB_PATH
        echo "LD_RUN_PATH=/opt/GCC/lib64" >> $GITHUB_ENV
          
    - name: validate gcc
      run: echo | g++ -xc++ -E --verbose -
      
    - name: build
      run: CXXVER=26 ./build.py /build_system /linux /process
